name: "python-todo-to-issue"
author: "Kevin Sawade <kevin.sawade@uni-konstanz.de>"
description: "Converts todos from comments and docstrings to issues."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "check-square"
  color: "orange"
inputs:
  TESTING:
    description: "For testing purposes. Let's the workflow run unittests from https://github.com/kevinsawade/python-todo-to-issue/blob/main/tests/test_todo_to_issue.py."
    required: false
    default: false
  TOKEN:
    description: "The GitHub access token."
    required: true
  CLOSE_ISSUES:
    description: "Whether to automatically close issues, that have been deleted in source code files."
    required: false
    default: true
