name: "Python todo to issue action"
author: "Kevin Sawade <kevin.sawade@uni-konstanz.de>"
description: "Converts todos from comments and google-style docstrings to issues."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "check-square"
  color: "orange"
inputs:
  TESTING:
    description: "For testing purposes. Let's the workflow run unittests"
    required: false
    default: false
  TOKEN:
    description: "The GitHub access token."
    required: true
  CLOSE_ISSUES:
    description: "Whether to automatically close issues, that have been deleted in source code files."
    required: false
    default: true
   REPO:
    description: "The path to the repository where the action will be used, e.g. 'kevinsawade/my-repo'."
    required: false
    default: "${{ github.repository }}"
  BEFORE:
    description: "The SHA of the last pushed commit."
    required: false
    default: "${{ github.event.before }}"
  SHA:
    description: "The SHA of the latest commit."
    required: false
    default: "${{ github.sha }}"
